server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shope-line_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: kirillshcherba92@gmail.com
#    password: Jumpjet_123
#    protocol: smtp
