server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop-line
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
